language: perl
sudo: false
perl:
    - "5.22"
    - "5.14"
    - "5.10"
cache:
    directories:
        - local
before_install:
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm Carton
install:
    - carton install
script:
    - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" carton exec prove -lrv t
after_success:
    - carton exec -- cover -report coveralls
